{
 "title": "HACert",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Basic System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ALL Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_logging_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Traefik Reload Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_traefik_reload", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Traefik Reload Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_traefik_reload_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Watcher Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_watcher_error", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Accepted Update",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_http_accepted_update", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Request Update",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_http_request_update", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Update Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_http_update_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Listener Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_http_listen_error", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Certificate File", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "File Change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_file_change", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "File Read Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_file_read_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "File Update",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_file_write", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "File Update Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_file_write_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "File Watcher Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_file_watcher_error", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Consul API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Consul API Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_api", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consul API Request Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_api_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consul GET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_get", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consul GET Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_get_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consul DEL ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_del", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consul DEL Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_del_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consul PUT ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_put", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consul PUT Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_put_error", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consul Undefine KV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hacert_consul_empty_get", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}